### ISSUE TITLE
MySQL problem.

### ISSUE THREAD

**Issue by chewupcheech** [TavstalDev/TShop2#13]
I have used both versions of Uconomy, but I constantly encounter the same error. I correctly receive rewards for kills, and my balance increases. But when I try to buy an item from the shop, the money does not charge, and the purchased item appears in the inventory. The console gives an error that you can see on the screen. Please help me solve this problem, because I really liked your plugin and would be happy to use it on my project.

![error](https://github.com/user-attachments/assets/feaa5cce-6fff-4349-b2fd-0a79ea7733b9)

**Comment by TavstalDev** [comment]
I have just tested with freshly downloaded tshop, uconomy and their libraries on a test server that I just created and it works.

So the issue is with Uconomy, or with the libraries. Maybe the mysql version is not compatible. 
Please try only use these [libraries](https://github.com/TavstalDev/TLibrary/releases/tag/1.0.8965.28889) (.zip file).
If the issue disappears then the problem is with libraries.

**Comment by chewupcheech** [comment]
I did everything according to your instructions, but the error still occurs. As you can see in the screenshots, I did it on a test server, without other plugins. It turns out that the problem is most likely in the version of MySQL. My version is 8.0.37 (I attached a screenshot below). So, which version should i try?

![libraries](https://github.com/user-attachments/assets/b10dbd1c-02c3-4ebf-89fd-900df9df7eb9)
![plugins](https://github.com/user-attachments/assets/fae53931-cfa4-48bd-8f70-2c330895f994)
![mysqlver](https://github.com/user-attachments/assets/8980432b-9a6e-406a-8eef-0f8b81b23629)
![logs](https://github.com/user-attachments/assets/4febf7eb-f569-4be2-9203-8c87cea121d0)

**Comment by chewupcheech** [comment]
I tried to test with experience mode and it works fine, but there is one problem:
I can sell a vehicle only when all the seats are occupied. When I try to sell any vehicle and there are free seats, I am kicked out of the vehicle and experience is awarded for the sale. Also, for some reason, the vehicle icons are not loading, I did not touch the links. I had a similar problem with the server icons after the last game update, and I had to change the hosting for the images.

https://github.com/user-attachments/assets/e6e298a8-0a45-40fa-9ef3-ce5e7c4aad8c

**Comment by TavstalDev** [comment]
Try use MySql 8.0.39 or 8.0.38. 

Could you try selling the vehicle again with the new plugin version that I just uploaded ?
But this time try selling it with command too not just by UI buttons.

**Comment by chewupcheech** [comment]
Updated MySQL and same error.
Tried fresh version, which you have upload yesterday. You can see the prolem with vehicles on video. Video was captured on clean test server. Selling with the command gives the same result.
Later i tried to load GlobalStatistic plugin and found a conflict (you can see console errors in the screens). 
Due to the conflict, the sale starts to work incorrectly. The item does not disappear from the inventory, but the money for the sale is credited.



https://github.com/user-attachments/assets/f242b910-c001-494e-bd3d-eb5c18bdeb03


![logs](https://github.com/user-attachments/assets/27f49453-507d-449f-9e8f-a448d838ce77)
![sellcommanderror](https://github.com/user-attachments/assets/946d106c-b44e-4109-a150-6cad7a39cc93)
![sellerror](https://github.com/user-attachments/assets/1ffaa80a-824b-48bb-a344-e32590ec9d05)
