### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by CatzMR** [TavstalDev/TShop2#16]
I found a problem. After I opened the Black Unbox UI, I could not open the TSHOP UI normally. Before opening the Black Unbox UI, I could open the TSHOP UI normally.
The inability to open the TSHOP UI normally here means that the interface will be blurred but the UI will not be displayed.
Black Unbox plugin link: https://unturnedstore.com/products/1665
Black Unbox creative workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=3303084230

**Comment by TavstalDev** [comment]
The issue is in Black Unbox.
