### ISSUE TITLE
Suspected useless storage？

### ISSUE THREAD

**Issue by MaoMao520twit** [TavstalDev/TShop2#6]
The DisplayName set in the database doesn't seem to be useful? (What is displayed in the UI is still set by the item file)

**Comment by TavstalDev** [comment]
If you speak about the DisplayName field in the icon folders then no, it is not an issue. 
It has nothing to do with the UI and it is not used anywhere except in the config file.
```
{
      "DispalyName": "0-2000", # <- this
      "FolderLink": "https://raw.githubusercontent.com/TavstalDev/Icons/master/Vanilla/",
      "MinItemId": 0,
      "MaxItemId": 2000
    }
```

**Comment by MaoMao520twit** [comment]
> DisplayName

I see, I hope that DisplayName can be set to be the name in the store if it can

**Comment by TavstalDev** [comment]
Check the ui_shopname translation key in the translation files.

**Comment by MaoMao520twit** [comment]
> ui_shopname

What I mean by this is to modify the name of each item in the UI through the database

**Comment by TavstalDev** [comment]
> the name of each item in the UI through the database

It is not possible at the moment. I might add it.
